eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: checkin-management
    preferIpAddress: true
server:
  port: 8084
spring:
  application:
    name: checkin-management
  data:
    mongodb:
      uri: >-
        mongodb+srv://balaji72118:U8D7YmO9FiXmTdpX@balaji.quhnxrr.mongodb.net/flight-booking-system
  

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/flightauth

    username: root
    password: 1707
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
rabbitmq:
  host: rabbitmq
  port: 5672
  username: balaji
  password: 1707

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.yourpackage: DEBUG  # replace with your base package